alias: NHL Goal Flash
description: Trigger WLED when a goal occurs
trigger:
  - platform: state
    entity_id: sensor.nhl_tor_mtl
    attribute: home
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.wled_living_room
    data:
      effect: "Flash"
      brightness: 255
      rgb_color: [255,0,0]
mode: single